version: "3.9"

services:
  db:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    shm_size: 128mb
    env_file:
      - .env.dev
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /app
    env_file: .env.dev
    depends_on:
      - db
    volumes:
      - ./:/app
